name: Issue matching auto-closer
description: Automatically close issues based on regexs matching.
author: arkon
branding:
  icon: alert-circle
  color: red
inputs:
  repo-token:
    required: true
    description: GitHub token
  ignoreLabel:
    description: Optional label name. If present, action is skipped.
  rules:
    required: true
    description: |
      A JSON-compliant string containing a list of rules, where a rule consists of:

      {
        type: 'title' | 'body' | 'both';  // Part to run regex against.
        regex: string;                    // Pattern which if matched closes the issue.
        message: string;                  // Message to post when closing the issue.
                                          // You can use {match} as a placeholder to the first match.
        ignoreCase: boolean | undefined;  // Defines if the regex will be case insensitive.
      }
  lock-command:
    required: false
    default: Lock this issue
    description: Command to be used to lock an issue.
  triage-team-slug:
    required: false
    default:
    description: Team from the organization with the members allowed to run commands.
runs:
  using: node12
  main: dist/index.js
