name: Issue closer test
on:
  issues:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Autoclose issue
      # uses: arkon/issue-closer-action@v3.4
      uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        ignoreLabel: do-not-autoclose
        rules: |
          [
            {
              "type": "title",
              "regex": ".*Test title.*",
              "message": "The title was not updated."
            },
            {
              "type": "body",
              "regex": ".*DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT.*",
              "message": "The acknowledgment section was not removed."
            },
            {
              "type": "body",
              "regex": ".*Test: \\?.*",
              "message": "The requested information was not filled out."
            },
            {
              "type": "both",
              "regex":".*(mangago|mangafox|hq\\s*dragon|manga\\s*host).*",
              "ignoreCase": true,
              "message": "{match} will not be added back as it is too difficult to maintain"
            }
          ]
